### ISSUE TITLE
Duplicate logging output

### ISSUE THREAD

**Issue by ariekahn** [mattcieslak/easy_lausanne#1]
Running python 2.7.10

Whenever I run easy_lausanne e.g. 
easy_lausanne --subject_id subj --target_volume scan.nii.gz --target_type diffusion --output_dir lausanne

I'm getting output like:

INFO     : 2015-06-08 10:38:03,463 : main       : T1 -> b0: BBREGISTER linear registration
INFO     : 2015-06-08 10:38:03,463 : main       : T1 -> b0: BBREGISTER linear registration
INFO     : 2015-06-08 10:38:03,463 : main       : ========================================
INFO     : 2015-06-08 10:38:03,463 : main       : ========================================
INFO     : 2015-06-08 10:38:03,463 : main       : Started FreeSurfer bbregister to find 'T1 --> b0' linear transformation
INFO     : 2015-06-08 10:38:03,463 : main       : Started FreeSurfer bbregister to find 'T1 --> b0' linear transformation

**Comment by mattcieslak** [comment]
Hello,

The duplicate printing was due to creating multiple loggers.  It wasn't running each step twice.  If you get the update it will run without duplicate printing.
