### ISSUE TITLE
Python error in reading the target volume in easy lausanne

### ISSUE THREAD

**Issue by akelkar26** [mattcieslak/easy_lausanne#7]
Hi,

I am having an issue with my newly installed Easy Lausanne software. The command isn't able to read the target volume and throws python errors. I echoed the target volume one step above and it exists but isn't read by the software. 

Here is my error:
Traceback (most recent call last):
  File "/data/jux/bdeck/anaconda3/bin/easy_lausanne", line 4, in <module>
    __import__('pkg_resources').run_script('Easy-Lausanne==0.5', 'easy_lausanne')
  File "/data/jux/bdeck/anaconda3/lib/python3.7/site-packages/pkg_resources/__init__.py", line 664, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/data/jux/bdeck/anaconda3/lib/python3.7/site-packages/pkg_resources/__init__.py", line 1450, in run_script
    script_code = compile(script_text, script_filename, 'exec')
  File "/data/jux/bdeck/anaconda3/lib/python3.7/site-packages/Easy_Lausanne-0.5-py3.7.egg/EGG-INFO/scripts/easy_lausanne", line 32
    print "Fatal: target volume does not exist", args.target_volume
                                              ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print("Fatal: target volume does not exist", args.target_volume)?

It get's stuck on this line of code:
${RUN} easy_lausanne --subject_id "${subject}" --target_volume "${workingdir}/${basenifti}" --target_type diffusion --output_dir "${lausannedir}" --include500 

Could you please help?

Thank you so much in advance. 

Thank you
Best,
Apoorva

**Comment by dbe5007** [comment]
I had the same problem when I tried to run it in Python 3. I switched over to using Python 2.7 and the error went away. Hope this helps!

**Comment by mattcieslak** [comment]
Yes, I never updated this package to python 3. Thanks for the report, closing for now
