### ISSUE TITLE
Error with linear transformation

### ISSUE THREAD

**Issue by chalex-eth** [mattcieslak/easy_lausanne#8]
Hello,

When I am trying to run : 
`easy_lausanne  --subject_id fsaverage  --target_volume /usr/local/freesurfer/subjects/fsaverage/mri/orig.mgz  --target_type bold  --output_dir /home/alex/MRI`

I got the following error : 

```
DEBUG    : 2020-04-22 13:53:21,670 : runCmd     : Running: convert_xfm -inverse /home/alex/MRI/b0-TO-orig.mat -omat /home/alex/MRI/orig-TO-b0.mat
DEBUG    : 2020-04-22 13:53:22,171 : runCmd     : Return Value: 0
DEBUG    : 2020-04-22 13:53:22,181 : runCmd     : Running: tkregister2 --regheader --mov /usr/local/freesurfer/subjects/fsaverage/mri/rawavg.mgz --targ /usr/local/freesurfer/subjects/fsaverage/mri/orig.mgz --regheader --reg /home/alex/MRI/T1-TO-orig.dat --fslregout /home/alex/MRI/T1-TO-orig.mat --noedit
INFO     : 2020-04-22 13:53:22,683 : main       : mghRead(/usr/local/freesurfer/subjects/fsaverage/mri/rawavg.mgz, -1): could not open file
INFO     : 2020-04-22 13:53:22,684 : main       : tkregister_tcl /usr/local/freesurfer/tktools/tkregister2.tcl
INFO     : 2020-04-22 13:53:22,684 : main       : target  volume /usr/local/freesurfer/subjects/fsaverage/mri/orig.mgz
INFO     : 2020-04-22 13:53:22,685 : main       : movable volume /usr/local/freesurfer/subjects/fsaverage/mri/rawavg.mgz
INFO     : 2020-04-22 13:53:22,685 : main       : reg file       /home/alex/MRI/T1-TO-orig.dat
INFO     : 2020-04-22 13:53:22,685 : main       : LoadVol        0
INFO     : 2020-04-22 13:53:22,685 : main       : ZeroCRAS       0
INFO     : 2020-04-22 13:53:22,686 : main       : $Id: tkregister2.c,v 1.132.2.1 2016/08/02 21:17:29 greve Exp $
INFO     : 2020-04-22 13:53:22,686 : main       : Diagnostic Level -1
INFO     : 2020-04-22 13:53:22,686 : main       : ERROR: could not read /usr/local/freesurfer/subjects/fsaverage/mri/rawavg.mgz as 3
CRITICAL : 2020-04-22 13:53:22,686 : runCmd     : Return Value: 1
DEBUG    : 2020-04-22 13:53:22,697 : runCmd     : Running: convert_xfm -omat /home/alex/MRI/T1-TO-b0.mat -concat /home/alex/MRI/orig-TO-b0.mat /home/alex/MRI/T1-TO-orig.mat
INFO     : 2020-04-22 13:53:23,198 : main       : Could not open matrix file /home/alex/MRI/T1-TO-orig.mat
INFO     : 2020-04-22 13:53:23,199 : main       : Cannot read input-matrix
CRITICAL : 2020-04-22 13:53:23,199 : runCmd     : Return Value: 254
ERROR    : 2020-04-22 13:53:23,200 : main       : An error occurred. Linear transformation file /home/alex/MRI/T1-TO-b0.mat not generated.
Traceback (most recent call last):
  File "/usr/local/bin/easy_lausanne", line 4, in <module>
    __import__('pkg_resources').run_script('Easy-Lausanne==0.5', 'easy_lausanne')
  File "/home/alex/.local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 666, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/home/alex/.local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1469, in run_script
    exec(script_code, namespace, namespace)
  File "/usr/local/lib/python2.7/dist-packages/Easy_Lausanne-0.5-py2.7.egg/EGG-INFO/scripts/easy_lausanne", line 79, in <module>
    
  File "build/bdist.linux-x86_64/egg/easy_lausanne/registration.py", line 77, in bb_regT12b0
Exception: An error occurred. Linear transformation file /home/alex/MRI/T1-TO-b0.mat not generated.

```

It seemed that the error comes from .mat file (I do not have matlab install, and scipy seemed to be correctly installed).

Do you have any idea where the error from ?

**Comment by julienbesle** [comment]
Hi Alex,

I got a similar error, although i can't be sure it's the same because the output you posted does not include the lines in which the error actually occurs, but only errors occurring as a consequence of that first error.

In my case, the error is due to a call to flirt.fsl within bbregister, which occurs a few lines before the error you posted.

The error only occurs for freesurfer v7.0.0, but not for freesurfer v6.0.0, so reverting back to freesurfer v6 solved it for me.

I sent an email to the freesurfer support list and we're looking into the problem with v7.0.0
https://www.mail-archive.com/freesurfer@nmr.mgh.harvard.edu/msg66127.html

I hope this helps

Best
Julien

**Comment by chalex-eth** [comment]
Hello Julien, 

My error was due to werd root access ..., after installing on a different path (and python 2.7 not 3.6), it seemed ok. 

You will also have to change the function nodes_iter by nodes or somtehing like this, because the networkx package have been updated.

**Comment by julienbesle** [comment]
Ok. Thanks. Different errors then.

Out of curiosity, can you tell me which version of freesurfer you're using?

Have you managed to get easy_lausanne to work till the end? 

I get other errors later on, one of which I describe in issue #9 but I've not yet got an error with networkx. It might depend on which version of the package is installed.

I also noticed that you use the freesurfer orig volume as your target. I think this is a T1-weighted image, right ? Did this work for you? From the easy_lausanne readme file, I thought it would work only for T2*-weighted volumes like BOLD or diffusion B=0, but if it did work for a T1-weighted, that would be great.

Thanks in advance for any tip.

Cheers
Julien

**Comment by chalex-eth** [comment]
I used Freesurfer 6.

Yes I finally managed to run the code but I still have an error, in the end the code doesn't work fully for me.
I just wanted to have the annot file in order to have the Lausanne parcellation in Brainstorm, so the input image doesn't matter for me. I just want to end with an annot file to create the atlas.

Sorry I cannot help you more, I struggled few weeks in order to have this parcellation. 

https://github.com/mattcieslak/easy_lausanne/issues/5

**Comment by julienbesle** [comment]
The code does not work fully for me either, but it does get far enough that it outputs the parcellations in volume (NIFTI format) and the annot files (all the files are output in the label folder of the freesurfer subject). I've not checked the annot files, but the volume parcellations look correct. 

Did you also get to this point when using the orig volume as target? and if yes, do the parcellations look correct?
Thanks

**Comment by chalex-eth** [comment]
Yes, I don't remenber when the code crash but I get the Nifti and the annot.

**Comment by julienbesle** [comment]
Ok. Thanks!
